name: Build emulator

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install libsdl2-dev
    - name: Build
      run: make
  cross-build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build for Windows
      run: |
        sudo apt-get install gcc-mingw-w64-i686
        pushd ..
        mkdir sdl2
        cd sdl2
        wget https://www.libsdl.org/release/SDL2-2.0.20.tar.gz
        tar xfz SDL2-2.0.20.tar.gz
        cd SDL2-2.0.20
        ./configure --host=i686-w64-mingw32
        make
        sudo make install
        popd
        i686-w64-mingw32-gcc-win32 -o risc src/sdl-main.c src/sdl-ps2.c src/risc.c src/risc-fp.c src/disk.c src/pclink.c src/raw-serial.c src/sdl-clipboard.c -g -Os -Wall -Wextra -Wconversion -Wno-sign-conversion -Wno-unused-parameter -std=c99 `/usr/local/cross-tools/i686-w64-mingw32/bin/sdl2-config --cflags --libs` -lm -mconsole
        i686-w64-mingw32-gcc-win32 -o riscw src/sdl-main.c src/sdl-ps2.c src/risc.c src/risc-fp.c src/disk.c src/pclink.c src/raw-serial.c src/sdl-clipboard.c -g -Os -Wall -Wextra -Wconversion -Wno-sign-conversion -Wno-unused-parameter -std=c99 `/usr/local/cross-tools/i686-w64-mingw32/bin/sdl2-config --cflags --libs` -lm -mwindows
    - name: Upload console binary
      uses: actions/upload-artifact@v2
      with:
        name: WindowsBinaries
        path: risc.exe
    - name: Upload windows binary
      uses: actions/upload-artifact@v2
      with:
        name: WindowsBinaries
        path: riscw.exe
